spring.application.name=stop-display-api
server.port=8080
gtfs.url=https://gtfsproxy.e-tam.fr/COMMON/GTFS.zip
gtfs.refresh-delay-ms=86400000
gtfs.load-on-startup=true
gtfs.retry.check-delay-ms=10000
gtfs.retry.base-delay-ms=30000
gtfs.retry.max-delay-ms=900000
gtfs.departures-limit=4
gtfs.trip-update.url=https://gtfsproxy.e-tam.fr/COMMON/TripUpdate.pb
gtfs.trip-update.refresh-delay-ms=30000
gtfs.trip-update.cache-ttl-ms=60000
gtfs.alert.url=https://gtfsproxy.e-tam.fr/COMMON/Alert.pb
gtfs.alert.refresh-delay-ms=30000
gtfs.alert.cache-ttl-ms=60000
gtfs.realtime.inspect.allowed-hosts=gtfsproxy.e-tam.fr
